### ISSUE TITLE
Choreonoid のプロジェクトファイルに含めた SDF/URDF モデルが読み込まれない

### ISSUE THREAD

**Issue by hmatsushita** [fkanehiro/choreonoid-sdfloader-plugin#13]
SDF/URDF モデルを読み込ませた後、Choreonoid のプロジェクトファイルとして保存、保存したプロジェクトファイルを読み込ませると、メッセージビューに下記のような警告が出力され SDF/URDF モデルの読み込みに失敗します。

```
"[モデルファイルへのパス]" はフォーマットが不明なため読み込めません。
Warning: "[モデル名]" を読み込むことができません。
```

Choreonoid を起動した端末へエラーや警告等の出力はありませんでした。

**Comment by fkanehiro** [comment]
修正しました（ 030a29a3ea96aae235480cc16784947cb972f498 ）
