### ISSUE TITLE
SDF モデルのジョイントタイプに revolute, prismatic, fixed 以外が含まれる場合、モデルの構造が破綻します 

### ISSUE THREAD

**Issue by hmatsushita** [fkanehiro/choreonoid-sdfloader-plugin#16]
SDF モデルのジョイントタイプに revolute, prismatic, fixed 以外が含まれる場合、モデルの構造が破綻します。
Gazebo が提供している PR2 モデル等で現象が確認できます。

動作検証は、simtrans で VRML 形式に変換したモデルとの比較で実施しました。
破綻内容は以下の通りです。

- リンク数が減少し、関節数が増加する

 VRML 形式の場合、リンク数 53・関節数 52 となっているのに対し、当該ローダで読み込んだ場合、リンク数 16・関節数 108 となります。

- ルートリンクとベースリンクが異なるリンクとなる

 VRML 形式の場合、ルートリンクとベースリンクが base_footprint となっているのに対し、当該ローダで読み込んだ場合、ルートリンクとベースリンクが r_gripper_r_parallel_link となります。

**Comment by yosuke** [comment]
PR2はjointの構造に循環があるモデルなので、ルートリンクの発見がうまく行かないことがあります。
ルートリンクの発見が失敗すると部分グラフしか見つからないのでこのようなことになります。

simtransの方は最新のPR2に対応したのですが、こちらはまだできていません。

**Comment by hmatsushita** [comment]
6ae7c4e で修正されている事を確認しました。
