### ISSUE TITLE
正しく読み込めない URDF モデルがあります

### ISSUE THREAD

**Issue by hmatsushita** [fkanehiro/choreonoid-sdfloader-plugin#6]
Ubuntu 14.04.3 環境を使用しています。

drcsim パッケージに含まれる atlas モデルの .xacro から URDF に変換したモデルを読み込ませたところ、いずれも正常にモデル表示ができません。
- atlas.urdf (atlas.urdf.xacro)
  
  読み込みは完了しますが、シーンビューに腰のパーツのみが表示される状態となります。
  リンクビューでは、正しいリンクツリーが構成されています。
- atlas_v3.urdf (atlas_v3.urdf.xacro)
  
  メッセージビューに以下のメッセージが出力され読み込みに失敗します。
  
  ```
  OpenHRP モデルファイル "/home/xxx/atlas_models/atlas_v3.urdf" を読み込み中
  [-1]It does not correspond to the colors of the polygon.-> 失敗.
  ```
- atlas_v4.urdf (atlas_v4.urdf.xacro)
  
  メッセージビューに以下のメッセージが出力され読み込みに失敗します。
  
  ```
  OpenHRP モデルファイル "/home/xxx/atlas_models/atlas_v4.urdf" を読み込み中
  -> 失敗.
  ```
- atlas_v5.urdf (atlas_v5.urdf.xacro)
  
  メッセージビューに以下のメッセージが出力され読み込みに失敗します。
  
  ```
  OpenHRP モデルファイル "/home/xxx/atlas_models/atlas_v5.urdf" を読み込み中
  -> 失敗.
  ```

URDF 変換後のモデルチェックは、check_urdf および、urdf_to_graphiz の出力結果で実施しています。
また、URDF に変換したモデルを simtrans で VRML 形式に変換、Choreonoid で読み込ませシミュレーションが実行できる事を確認しています。

**Comment by hmatsushita** [comment]
PR2 モデル (https://github.com/PR2/pr2_common.git) の pr2_description/robots/pr2_no_kinect.urdf.xacro を URDF に変換したモデルについても試してみましたが、こちらも読み込みに失敗しました。
メッセージビューには、以下のメッセージが出力されています。

```
OpenHRP モデルファイル "/home/mat/tmp/pr2_no_kinect.urdf" を読み込み中
-> 失敗.
```

また、Choreonoid を起動したコンソールには、以下のメッセージが出力されています。

```
Warning [parser_urdf.cc:1071] multiple inconsistent <gravity> exists due to fixed joint reduction overwriting previous value [true] with [false].
Warning [parser_urdf.cc:1071] multiple inconsistent <gravity> exists due to fixed joint reduction overwriting previous value [false] with [true].
Warning [parser.cc:713] XML Element[initial_joint_position], child of element[joint] not defined in SDF. Ignoring[initial_joint_position]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
Warning [parser.cc:713] XML Element[initial_joint_position], child of element[joint] not defined in SDF. Ignoring[initial_joint_position]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
model name pr2
 link name base_footprint
 link name bl_caster_rotation_link
  read mesh /opt/ros/indigo/share/pr2_description/meshes/base_v0/caster.stl
  read mesh /opt/ros/indigo/share/pr2_description/meshes/base_v0/caster_L.stl
 link name bl_caster_l_wheel_link
  read mesh /opt/ros/indigo/share/pr2_description/meshes/base_v0/wheel.dae
std::exception
```

**Comment by yosuke** [comment]
#5 の問題についても殆どそうなのですが、dae（collada）形式を読み込む機能が不十分で様々な問題が出ています。

colladaファイルはXML形式でモデルの形状を記述するのですが、記述に自由度が高く、オーサリングソフトによって出力形式がバラバラなためこのような問題が起こります。

choreonoidのdaeファイル読み込み機能を強化するか、実績のある強力な外部の読み込みライブラリ（assimpなど）を使うかの対処を行う予定ですのでもう少々お待ちください。

**Comment by hmatsushita** [comment]
227ef3f で PR2 モデルが問題なく読み込める事を確認しました。
atlas については、近いうちに確認を実施する予定です。

**Comment by hmatsushita** [comment]
申し訳ございません。
チケットをクローズする事を忘れておりました。

atlas モデルがいずれも問題なく読み込める事を確認しました。
