### ISSUE TITLE
SDF モデルの質量の設定値が Choreonoid のプロパティに反映されていません

### ISSUE THREAD

**Issue by hmatsushita** [fkanehiro/choreonoid-sdfloader-plugin#8]
Ubuntu 14.04.3 環境を使用しています。

https://bitbucket.org/osrf/gazebo_models/src/a8fbd980b60c?at=default で公開されている SDF モデルより、当該プラグインで読み込み可能な下記のモデルにおいて質量設定 (mass 要素) がなされていますが、いずれも Choreonoid のプロパティ「質量」 に反映されていません (常に 0.000)。

- drc_practice_hand_wheel_valve (0.0644)

- drc_practice_handle_wheel_valve (4.6114)

- drc_practice_truss (20.7307)

- drc_practice_wheel_valve (7.9917)

- drc_practice_wheel_valve_large (7.8219)

上記モデル以外では、http://gazebosim.org/models で公開されている SDF モデル coke_can が 0.390 となっていますが、同様に反映されていませんでした。

**Comment by hmatsushita** [comment]
e064097 の修正で、質量設定が正しく反映される事を確認しました。
本 issue で挙げたモデル以外に、simtrans で URDF 形式に変換した JVRC-1 モデルについても、正しく反映される事を確認しました。

**Comment by yosuke** [comment]
大丈夫そうでしたらcloseしてもらえるでしょうか？

**Comment by hmatsushita** [comment]
申し訳ありません close するのを忘れていました。
